export const translations = {
  ee: {
    pageTitle: 'HELI - Tallinna klubiskeene showcase festival',
    nav: { programme: 'Programm', venues: 'Paigad', artists: 'Artistid', transport: 'Transport', info: 'Info' },
    language: { label: 'Vali keel', ee: 'EE', en: 'EN' },
    common: { placeholder: 'Näidis', programmePlaceholder: 'Programmi näidis', backToProgramme: 'Tagasi programmi juurde', clearFilters: 'Tühjenda filtrid', date: 'Kuupäev', venue: 'Toimumispaik', format: 'Vorming', all: 'Kõik' },
    header: { ticket: 'Pilet - 15 €', footerNote: 'Programmi detailid on näidisena, kuni koosseis on avalik.' },
    home: { identity: 'Tallinna<br>klubiskeene<br>showcase<br>festival', intro: 'Üks pilet kaheks õhtuks avastada Tallinna peidetud pärleid.', programme: 'Vaata programmi', ticketsAction: 'Osta pilet', conceptTitle: 'HELI Fest on liikuv fest.', conceptText: 'HELI toob Tallinna klubid kaheks õhtuks kokku. Vali set, hüppa bussi peale ja vaata, kuhu õhtu viib.', transport: 'Transport ja paigad', startHere: 'Alusta siit', routeTitle: 'Tänane teekond.', fullProgramme: 'Vaata kogu programmi', pass: 'Festivalipilet', passText: 'Pilet kehtib osalevates kohtades ja festivalitranspordis. Seda saab osta või kätte saada koha ja bussi ukselt.', passDetails: 'Piletiinfo', featuredVenue: 'Paavli<br>Kultuurivabrik', featuredVenueTitle: 'Üks õhtu. Üks linn.', featuredVenueBody: 'HELI toob Tallinna klubid kaheks õhtuks kokku. Paavli Kultuurivabrik on üks festivali osalevatest paikadest, kus õhtu saab alguse.', featuredVenueAction: 'Vaata paika', heroCaption: 'Tallinna klubiskeene kahe õhtu showcase-festival.', marqueeDate: 'GET YOUR TICKET NOW', marqueeRoute: 'GET YOUR TICKET NOW', marqueeLabel: 'Festivali kuupäevad', openCall: 'Open call', mapTitle: 'Tallinna kaart', mapAlt: 'HELI geomeetriline Tallinna kaart', iconRowLabel: 'Paigad ja partnerid' },
    route: { label: 'Festivali marsruut', shuttle: 'HELI buss', passRequired: 'Vajalik on festivalipilet' },
    programme: { label: 'Programm / marsruudi ajakava', title: 'Jälgi<br>ööd.', intro: 'Esinejate nimekiri ja ajakava on veel avaldamisel. Need read näitavad, kuidas programm toimib.', result: (count) => `${count} ${count === 1 ? 'näidisrida' : 'näidisrida'} sellel marsruudil`, emptyTitle: 'Ükski valik ei sobi.', emptyText: 'Proovi teist kuupäeva või tühjenda filtrid.', live: 'Live', dj: 'DJ-set', listening: 'Kuulamine' },
    venues: { label: 'Osalevad paigad', title: 'Palju ruume.<br>Üks teekond.', stop: 'bussipeatus', onRoute: 'HELI marsruudil.', description: 'Koht lisab oma tutvustuse enne festivali.', address: 'Aadress', accessibility: 'Ligipääsetavus', accessibilityTbd: 'Ligipääsetavuse info lisandub peagi.', transport: 'Transport', atVenue: 'Selles kohas' },
    artists: { label: 'Artistid', title: 'Artistid,<br>peagi.', intro: 'Artistide info tuleb koos täieliku programmiga.', toBeAnnounced: 'Artist avalikustamisel', bio: 'Festivali tiim lisab artisti tutvustuse koos esinejate nimekirjaga.', social: 'Sotsiaal- ja helilingid lisatakse koos artisti avalikustamisega.', appearances: 'Näidisesinemised' },
    tickets: { label: 'Festivalipilet', intro: 'Üks pilet osalevatesse kohtadesse ja festivalitransporti mõlemal õhtul.', venues: 'Kohtades', venuesText: 'Pileteid müüakse ja kontrollitakse osalevates kohtades.', shuttle: 'Bussis', shuttleText: 'Festivali buss on festivalipileti omanikele.', collection: 'Kättesaamine', collectionText: 'Eelmüügist ostetud pileti saab kätte koha või bussi ukselt.', linkNote: 'Korraldaja lisab ostulingi.', stops: 'Vaata bussipeatusi' },
    transport: { label: 'Transport / paigad', title: 'Teekond on<br>festival.', description: 'Festivali buss sõidab mõlemal õhtul osalevate kohtade vahel. Väljumisajad avaldatakse enne festivali.', stops: 'Bussipeatused', nearby: 'Lähedal asuvad osalevad paigad', before: 'Enne minekut', buses: 'Õhtu jooksul sõidab kohtade vahel ringis kolm või neli bussi.', times: 'Festivali tiim avaldab väljumisajad enne üritust.', venuesByStop: 'Vaata paiku peatuse järgi' },
    info: { label: 'Festivalist / kontakt', title: 'Üks linn.<br>Ühes rütmis.', intro: 'HELI on kaks õhtut muusikat Tallinna sõltumatutes klubides.', what: 'Mis on HELI?', whatText: 'Kahepäevane Tallinna klubiskeene showcase, mis toob kohad, artistid ja publiku ühe programmi alla.', safety: 'Turvalisus ja vanusepiirangud', safetyText: 'Iga koha reeglid avaldatakse koos täisprogrammiga.', accessibility: 'Ligipääsetavus', accessibilityText: 'Ligipääsetavuse info ilmub iga koha lehel.', contact: 'Kontakt ja partnerid', contactText: 'Korraldaja lisab siia kontakt- ja partnerinfo.' },
    notFound: { label: 'Marsruuti ei leitud', title: 'Vali teine<br>peatus.', action: 'Ava programm' },
  },
  en: {
    pageTitle: 'HELI - Tallinn club scene showcase festival',
    nav: { programme: 'Programme', venues: 'Venues', artists: 'Artists', transport: 'Transport', info: 'Info' },
    language: { label: 'Choose language', ee: 'EE', en: 'EN' },
    common: { placeholder: 'Placeholder', programmePlaceholder: 'Programme placeholder', backToProgramme: 'Back to programme', clearFilters: 'Clear filters', date: 'Date', venue: 'Venue', format: 'Format', all: 'All' },
    header: { ticket: 'Pass - EUR15', footerNote: 'Programme details are placeholders until the line-up is announced.' },
    home: { identity: 'Tallinn<br>club scene<br>showcase<br>festival', intro: 'One pass for two nights across Tallinn\'s independent venues.', programme: 'See the programme', ticketsAction: 'Buy a pass', conceptTitle: 'A festival that moves.', conceptText: 'HELI brings Tallinn\'s clubs together for two nights. Pick a set, take the shuttle, then see where the evening goes.', transport: 'See transport and locations', startHere: 'Start here', routeTitle: 'Tonight\'s route.', fullProgramme: 'View full programme', pass: 'Festival pass', passText: 'The pass is valid at participating venues and on festival transport. You can buy or collect it at venue and shuttle doors.', passDetails: 'Pass details', featuredVenue: 'Paavli<br>Kultuurivabrik', featuredVenueTitle: 'One night. One city.', featuredVenueBody: 'HELI brings Tallinn\'s clubs together for two nights. Paavli Kultuurivabrik is one of the participating festival venues where the evening begins.', featuredVenueAction: 'See venue', heroCaption: 'Tallinn club scene showcase festival across two nights.', marqueeDate: 'GET YOUR TICKET NOW', marqueeRoute: 'GET YOUR TICKET NOW', marqueeLabel: 'Festival dates', openCall: 'Open call', mapTitle: 'Tallinn map', mapAlt: 'HELI geometric Tallinn map', iconRowLabel: 'Venues and partners' },
    route: { label: 'Festival route', shuttle: 'HELI shuttle', passRequired: 'Festival pass required' },
    programme: { label: 'Programme / route timetable', title: 'Follow<br>the night.', intro: 'The line-up and timetable are still being announced. These entries show how the programme will work.', result: (count) => `${count} ${count === 1 ? 'placeholder entry' : 'placeholder entries'} on this route`, emptyTitle: 'Nothing matches these filters.', emptyText: 'Try another date or clear the filters.', live: 'Live', dj: 'DJ set', listening: 'Listening' },
    venues: { label: 'Participating venues', title: 'Many rooms.<br>One route.', stop: 'shuttle stop', onRoute: 'On the HELI route.', description: 'The venue will add its own description before the festival.', address: 'Address', accessibility: 'Accessibility', accessibilityTbd: 'Accessibility information is still to come.', transport: 'Transport', atVenue: 'At this venue' },
    artists: { label: 'Artists', title: 'Artists,<br>soon.', intro: 'Artist details will arrive with the full programme.', toBeAnnounced: 'Artist to be announced', bio: 'The festival will add the artist biography with the line-up announcement.', social: 'Social and audio links will be added with the artist announcement.', appearances: 'Placeholder appearances' },
    tickets: { label: 'Festival pass', intro: 'One pass for participating venues and festival transport on both nights.', venues: 'At venues', venuesText: 'Pass sales and checks take place at participating locations.', shuttle: 'On the shuttle', shuttleText: 'The shuttle is for festival pass holders.', collection: 'Collection', collectionText: 'Collect a pre-purchased pass at a venue or shuttle door.', linkNote: 'The organiser will add the purchase link.', stops: 'See shuttle stops' },
    transport: { label: 'Transport / locations', title: 'The route<br>is the festival.', description: 'The festival shuttle runs between participating venues on both nights. Departure times will be announced closer to the festival.', stops: 'Shuttle stops', nearby: 'Participating venues nearby', before: 'Before you go', buses: 'Three or four buses will run in rotation between participating venues all evening.', times: 'The festival team will publish route times before the event.', venuesByStop: 'See venues by stop' },
    info: { label: 'About / contact', title: 'One city.<br>In concert.', intro: 'HELI is two nights of music across Tallinn\'s independent clubs.', what: 'What is HELI?', whatText: 'A two-day Tallinn club-scene showcase that brings venues, artists and audiences into one programme.', safety: 'Safety and age restrictions', safetyText: 'Each venue\'s policy will be published with the full programme.', accessibility: 'Accessibility', accessibilityText: 'Accessibility information will appear on each venue page.', contact: 'Contact and partners', contactText: 'The organiser will add contact and partner information here.' },
    notFound: { label: 'Route not found', title: 'Choose<br>another stop.', action: 'Go to programme' },
  },
};

export function translate(locale, path) {
  return path.split('.').reduce((value, key) => value?.[key], translations[locale]) ?? path;
}
