export const sponsorLogos = [
  { src: '/assets/sponsors/paavli-kultuurivabrik.svg', alt: 'Paavli Kultuurivabrik', title: 'Paavli Kultuurivabrik', href: 'https://www.kultuurivabrik.ee/', opticalScale: 0.86 },
  { src: '/assets/sponsors/ida.svg', alt: 'IDA', title: 'IDA', href: 'https://www.idaidaida.ee/', opticalScale: 0.9 },
  { src: '/assets/sponsors/hall.svg', alt: 'HALL', title: 'HALL', href: 'https://hall.vision/', opticalScale: 0.84 },
  { src: '/assets/sponsors/kumu.svg', alt: 'Kumu', title: 'Kumu', href: 'https://kumu.ekm.ee/', opticalScale: 0.92 },
  { src: '/assets/sponsors/d3.svg', alt: 'D3', title: 'D3', href: 'https://www.d-3.ee/', opticalScale: 0.95 },
  { src: '/assets/sponsors/mod.svg', alt: 'MOD', title: 'MOD', href: 'https://modclub.ee/', opticalScale: 0.88 },
  { src: '/assets/sponsors/ekkm.svg', alt: 'EKKM', title: 'EKKM', href: 'https://www.ekkm.ee/', opticalScale: 0.95 },
  { src: '/assets/sponsors/hungr.svg', alt: 'Hungr', title: 'Hungr', href: 'https://starving.me/', opticalScale: 1.1 },
  { src: '/assets/sponsors/uus-laine.svg', alt: 'Uus Laine', title: 'Uus Laine', href: 'https://uuslaine.com/', opticalScale: 1.1 },
  { src: '/assets/sponsors/ulase-12.svg', alt: 'Ülase 12', title: 'Ülase 12', href: 'https://www.instagram.com/ylase12/', opticalScale: 1.05 },
  { src: '/assets/sponsors/fonoteek.svg', alt: 'FONOTEEK', title: 'FONOTEEK', href: 'https://fonoteek.ee/', opticalScale: 1 },
  { src: '/assets/sponsors/tops.svg', alt: 'TOPS', title: 'TOPS', href: 'https://www.facebook.com/kohviktops/', opticalScale: 0.92 },
  { src: '/assets/sponsors/plastik.svg', alt: 'Plastik', title: 'Plastik', href: 'https://www.plastikrecords.ee/', opticalScale: 1.1 },
  { src: '/assets/sponsors/kureeritud-uudised-records.svg', alt: 'Kurvad Uudised Records', title: 'Kurvad Uudised Records', href: 'https://www.kurvaduudised.com/', opticalScale: 1.08 },
  { src: '/assets/sponsors/von-krahl.svg', alt: 'Von Krahl', title: 'Von Krahl', href: 'https://vonkrahl.ee/', opticalScale: 1 },
  { src: '/assets/sponsors/eka.svg', alt: 'EKA', title: 'EKA', href: 'https://www.artun.ee/', opticalScale: 1 },
  { src: '/assets/sponsors/biit-me.svg', alt: 'Biit Me', title: 'Biit Me', href: 'https://biit.me/', opticalScale: 1.05 },
  { src: '/assets/sponsors/kino-soprus.svg', alt: 'Kino Sõprus', title: 'Kino Sõprus', href: 'https://kinosoprus.ee/', opticalScale: 1 },
  { src: '/assets/sponsors/xinh.svg', alt: 'Xinhai 1911', title: 'Xinhai 1911', href: 'https://wolt.com/en/est/tallinn/restaurant/xinhai-1911-restaurant-bar', opticalScale: 1 },
  { src: '/assets/sponsors/pudel.svg', alt: 'Pudel', title: 'Pudel', href: 'https://pudel.ee/', opticalScale: 1 },
  { src: '/assets/sponsors/stuudio.svg', alt: 'Stuudio', title: 'Stuudio', href: 'https://clubstudio.ee/', opticalScale: 1.05 },
  { src: '/assets/sponsors/burger-box.svg', alt: 'Burger Box', title: 'Burger Box', href: 'https://www.facebook.com/burgerboxbox/', opticalScale: 1.05 },
  { src: '/assets/sponsors/terminal.svg', alt: 'Terminal', title: 'Terminal', href: 'https://terminal.ee/', opticalScale: 1.1 },
  { src: '/assets/sponsors/tallinn.svg', alt: 'Tallinn', title: 'Tallinn', href: 'https://www.tallinn.ee/', opticalScale: 1 },
];
