export const sponsorLogos = [
  { src: '/assets/sponsors/paavli-kultuurivabrik.png', alt: 'Paavli Kultuurivabrik', title: 'Paavli Kultuurivabrik' },
  { src: '/assets/sponsors/ida.png', alt: 'IDA', title: 'IDA' },
  { src: '/assets/sponsors/hall.png', alt: 'HALL', title: 'HALL' },
  { src: '/assets/sponsors/kumu.png', alt: 'Kumu', title: 'Kumu' },
  { src: '/assets/sponsors/d3.png', alt: 'D3', title: 'D3' },
  { src: '/assets/sponsors/mod.png', alt: 'MOD', title: 'MOD' },
  { src: '/assets/sponsors/ekkm.png', alt: 'EKKM', title: 'EKKM' },
  { src: '/assets/sponsors/hungr.png', alt: 'Hungr', title: 'Hungr' },
  { src: '/assets/sponsors/uus-laine.png', alt: 'Uus Laine', title: 'Uus Laine' },
  { src: '/assets/sponsors/ulase-12.png', alt: 'Ülase 12', title: 'Ülase 12' },
  { src: '/assets/sponsors/fonoteek.png', alt: 'FONOTEEK', title: 'FONOTEEK' },
  { src: '/assets/sponsors/tops.png', alt: 'TOPS', title: 'TOPS' },
  { src: '/assets/sponsors/plastik.png', alt: 'Plastik', title: 'Plastik' },
  { src: '/assets/sponsors/kureeritud-uudised-records.png', alt: 'Kureeritud Uudised Records', title: 'Kureeritud Uudised Records' },
  { src: '/assets/sponsors/von-krahl.png', alt: 'Von Krahl', title: 'Von Krahl' },
  { src: '/assets/sponsors/eka.png', alt: 'EKA', title: 'EKA' },
  { src: '/assets/sponsors/biit-me.png', alt: 'Biit Me', title: 'Biit Me' },
  { src: '/assets/sponsors/kino-soprus.png', alt: 'Kino Sõprus', title: 'Kino Sõprus' },
  { src: '/assets/sponsors/xinh.png', alt: 'XINH', title: 'XINH' },
  { src: '/assets/sponsors/pudel.png', alt: 'Pudel', title: 'Pudel' },
  { src: '/assets/sponsors/stuudio.png', alt: 'Stuudio', title: 'Stuudio' },
  { src: '/assets/sponsors/burger-box.png', alt: 'Burger Box', title: 'Burger Box' },
  { src: '/assets/sponsors/terminal.png', alt: 'Terminal', title: 'Terminal' },
  { src: '/assets/sponsors/tallinn.png', alt: 'Tallinn', title: 'Tallinn' },
];
