export const sponsorLogos = [
  { src: '/assets/sponsors/paavli-kultuurivabrik.svg', alt: 'Paavli Kultuurivabrik', title: 'Paavli Kultuurivabrik' },
  { src: '/assets/sponsors/ida.svg', alt: 'IDA', title: 'IDA' },
  { src: '/assets/sponsors/hall.svg', alt: 'HALL', title: 'HALL' },
  { src: '/assets/sponsors/kumu.svg', alt: 'Kumu', title: 'Kumu' },
  { src: '/assets/sponsors/d3.svg', alt: 'D3', title: 'D3' },
  { src: '/assets/sponsors/mod.svg', alt: 'MOD', title: 'MOD' },
  { src: '/assets/sponsors/ekkm.svg', alt: 'EKKM', title: 'EKKM' },
  { src: '/assets/sponsors/hungr.svg', alt: 'Hungr', title: 'Hungr' },
  { src: '/assets/sponsors/uus-laine.svg', alt: 'Uus Laine', title: 'Uus Laine' },
  { src: '/assets/sponsors/ulase-12.svg', alt: 'Ülase 12', title: 'Ülase 12' },
  { src: '/assets/sponsors/fonoteek.svg', alt: 'FONOTEEK', title: 'FONOTEEK' },
  { src: '/assets/sponsors/tops.svg', alt: 'TOPS', title: 'TOPS' },
  { src: '/assets/sponsors/plastik.svg', alt: 'Plastik', title: 'Plastik' },
  { src: '/assets/sponsors/kureeritud-uudised-records.svg', alt: 'Kureeritud Uudised Records', title: 'Kureeritud Uudised Records' },
  { src: '/assets/sponsors/von-krahl.svg', alt: 'Von Krahl', title: 'Von Krahl' },
  { src: '/assets/sponsors/eka.svg', alt: 'EKA', title: 'EKA' },
  { src: '/assets/sponsors/biit-me.svg', alt: 'Biit Me', title: 'Biit Me' },
  { src: '/assets/sponsors/kino-soprus.svg', alt: 'Kino Sõprus', title: 'Kino Sõprus' },
  { src: '/assets/sponsors/xinh.svg', alt: 'XINH', title: 'XINH' },
  { src: '/assets/sponsors/pudel.svg', alt: 'Pudel', title: 'Pudel' },
  { src: '/assets/sponsors/stuudio.svg', alt: 'Stuudio', title: 'Stuudio' },
  { src: '/assets/sponsors/burger-box.svg', alt: 'Burger Box', title: 'Burger Box' },
  { src: '/assets/sponsors/terminal.svg', alt: 'Terminal', title: 'Terminal' },
  { src: '/assets/sponsors/tallinn.svg', alt: 'Tallinn', title: 'Tallinn' },
];
